import type { Metadata } from "next";
import {Geist, Geist_Mono, Josefin_Sans, Montserrat, Quicksand, Roboto, Roboto_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import Layout from "@/components/layouts/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistMonserrat = Josefin_Sans({
 weight:['300','400','500','600','700'],
  subsets: ["latin"],
  display:'swap',
    variable: '--font-geist-monserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistMonserrat.className} antialiased`}
      >
      <ThemeProvider attribute="class" enableSystem>
            <Layout>
                {children}
            </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
